  tap "homebrew/bundle"
  tap "d12frosted/emacs-plus"
  tap "caskroom/fonts"
  tap "caskroom/cask"
  brew "ack"
  brew "aspell"
  brew "automake"
  brew "coreutils"
  brew "ctags"
  brew "ditaa"
  brew "docbook"
  brew "fish", args: ["HEAD"]
  brew "fop"
  brew "gpg2", args: ["with-readline"]
  brew "pkg-config"
  brew "isync"
  brew "msmtp"
  brew "mu", args: ["with-emacs"]
  brew "neovim", args: ["HEAD"]
  brew "node"
  brew "p7zip"
  brew "pandoc"
  brew "phantomjs"
  brew "pidof"
  brew "poppler"
  brew "rclone"
  brew "rlwrap"
  brew "saxon"
  brew "sshfs"
  brew "terminal-notifier"
  brew "the_silver_searcher"
  brew "tmux"
  brew "trash"
  brew "tree"
  brew "vim", args: ["with-gettext", "with-lua", "with-override-system-vi"]
  brew "w3m"
  brew "watch"
  brew "d12frosted/emacs-plus/emacs-plus", args: ["with-natural-title-bar"]
  cask "calibre"
  cask "cyberduck"
  cask "dash"
  cask "spotify"
  cask "virtualbox"
  cask "caskroom/fonts/font-fira-code"
  cask "caskroom/fonts/font-menlo-for-powerline"
  cask "caskroom/fonts/font-source-code-pro"

